# Generated by Django 4.2.3 on 2023-07-06 01:48

from django.db import migrations, models
import jornada.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('depoimento', models.TextField()),
                ('foto', models.ImageField(upload_to=jornada.models.Depoimento.upload_path)),
            ],
        ),
    ]
