# Generated by Django 4.2.3 on 2023-07-08 01:13

from django.db import migrations, models
import jornada.models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='foto',
            field=models.ImageField(blank=True, upload_to=jornada.models.Depoimento.upload_path),
        ),
    ]
