# Generated by Django 4.2.3 on 2023-07-23 13:52

from django.db import migrations, models
import jornada.models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0002_alter_depoimento_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to=jornada.models.Destino.upload_path)),
            ],
        ),
    ]
