# Generated by Django 4.2.3 on 2023-08-01 01:27

from django.db import migrations, models
import jornada.models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0003_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='foto',
            field=models.ImageField(blank=True, upload_to=jornada.models.Destino.upload_path),
        ),
        migrations.AlterField(
            model_name='destino',
            name='preco',
            field=models.CharField(max_length=20),
        ),
    ]
