# Generated by Django 4.2.3 on 2023-08-01 02:18

from django.db import migrations, models
import jornada.models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0004_alter_destino_foto_alter_destino_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destino',
            old_name='foto',
            new_name='foto_1',
        ),
        migrations.AddField(
            model_name='destino',
            name='foto_2',
            field=models.ImageField(blank=True, upload_to=jornada.models.Destino.upload_path),
        ),
        migrations.AddField(
            model_name='destino',
            name='meta',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='destino',
            name='texto_descritivo',
            field=models.TextField(blank=True),
        ),
    ]
